# Generated by Django 3.0.1 on 2020-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscribers_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='videos_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='views_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='average_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='average_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes_count',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='views_count',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
