# Generated by Django 3.0.1 on 2023-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='current_page_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='next_page_token',
            field=models.CharField(max_length=255),
        ),
    ]
