# Generated by Django 3.0.1 on 2020-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountInfo', '0002_auto_20200129_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
